
// 사물 인증서 (파일 이름: xxxxxxxxxx-certificate.pem.crt)
const char cert_str[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVAKvw11NXnp0708SI2HKzH9BEicM/MA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMTA3MDExMTU4
MTZaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMa0kjLXw2e7vS/hZD
-----END CERTIFICATE-----
)EOF";
// 사물 인증서 프라이빗 키 (파일 이름: xxxxxxxxxx-private.pem.key)
const char key_str[] PROGMEM = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAzGtJIy18Nnu70v4WQ9u7mPZr3f3R9Stc8FTk1HKYBottxMqs
p/XioZzVV8M8FzoIy7+Sf1O3TDjDPfZpVO5XfcAx5k+awvxz0qC5okNlu8jPxquK
8wPzS/Bo4NUJ7luB0hyAW2p9CuIKIxxWOwrRULQrEKlhY9QY1KLfvqId8GiR3Z/9
AXDl7gAckHqK1T5q12BCNB0B/hK2mM2wiyIrfYmYLBgTChGlAkeEfEGB+1CEdR/W
hyF0mcZMsgUp5J9msFgGbuK+LHkc9gJRQDlJOlRPyj68Hs3uNijsmS2c0ZfeMfCl
U/G6hR9UB2+x9t5mTj8EXb44r8PmSu5R9+jw1QIDAQABAoIBAGlWI5L//lDpA8le
60Q+d3YEDWOQRt/qX3LsnBopjtNYh9Dvi3blisoy0fDuhwmE+0Faz3fTQNIDMgC8
-----END RSA PRIVATE KEY-----

)EOF";
// Amazon Trust Services(ATS) 엔드포인트 CA 인증서 (서버인증 > "RSA 2048비트 키: Amazon Root CA 1" 다운로드)
const char ca_str[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
-----END CERTIFICATE-----
)EOF";
