// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUJN/k8RYMT4Q7VwcIGMrhAkcu2e8wDQYJKoZIhvcNAQEL
2b6+1C573oYzjAWRhBK6dAjVD8jUtu9/mKiTllta03oHAyvYbxtDZkKw7AggjSza
RxpCqJxDCmAUNIOCTe2ZzbUVJJlmw1twZ6EmdT9fEW+1q+K9t8HTSgf5cX1H
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAzKhG5h0u/kLIdL8DvK7HJwHonJVFuDzKdtdNbtTcWIrgKYBR
ke69xO8NYMkreoLWp4psn0cNqb5x47TpyQSujUiHYTnvCRQgbZBCqUofMZcL7UKI
-----END RSA PRIVATE KEY-----
)KEY";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
-----END CERTIFICATE-----
)EOF";

//Enter the name of your AWS IoT thing, MyNewESP
