
// 사물 인증서 (파일 이름: xxxxxxxxxx-certificate.pem.crt)
const char cert_str[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUbg0DGDvO3B7IksjHHiah750dnkswDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIyMDExMTA0Mjkz
NFoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKfGtyitZlo7o3i7kskf
u6tYCs67L5md3Ev7xi7aFon/H9qlkDUYsCRB/U4dizNrg//slnPJGkPV/ilSU6Vz
i6LrD0nWY62W4UoyPlZ6qOEm2T0fWbQo3iGSqh8ixE9WiFBiyUAGr8XWX5VF87+k
XNJjbkU6tVVsUDXtkLvc42Jf5B/Bxrmq5FW82EaoVWHxo+JlxYAtDF/v1WQpVl2Q
flB/7VU6VCGTKwvFLAPDpCDnuY2QaPuaYetpIh7yz6fvN47BApScgDTPeyDpI0s/
2YKwecmIfe/1NBAsls5lpLj6cVxpe2ZVqEczr6LTY6nr4pF5OEtWCqHbjzmt9l/X
-----END CERTIFICATE-----

)EOF";
// 사물 인증서 프라이빗 키 (파일 이름: xxxxxxxxxx-private.pem.key)
const char key_str[] PROGMEM = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAp8a3KK1mWjujeLuSyR+7q1gKzrsvmZ3cS/vGLtoWif8f2qWQ
NRiwJEH9Th2LM2uD/+yWc8kaQ9X+KVJTpXOLousPSdZjrZbhSjI+Vnqo4SbZPR9Z
tCjeIZKqHyLET1aIUGLJQAavxdZflUXzv6Rc0mNuRTq1VWxQNe2Qu9zjYl/kH8HG
uarkVbzYRqhVYfGj4mXFgC0MX+/VZClWXZB+UH/tVTpUIZMrC8UsA8OkIOe5jZBo
+5ph62kiHvLPp+83jsEClJyANM97IOkjSz/ZgrB5yYh97/U0ECyWzmWkuPpxXGl7
ZlWoRzOvotNjqevikXk4S1YKoduPOa32X9fzGwIDAQABAoIBAQCJxIQsM88DM0u1
3RjYbGVXerFNNqoMk3MNNc50NIMjh8ppaWB0KTSiYUmWNm5Sp+u5YFXe9/jIUVUm
K0MibjHwcuKX+CLbrTSMD5veuVQpphPmu/KWHKTinqNxc8QNffnrQGMPXy5A3xqX
4dwYtue9nwYydNXoMkvfLJeXm/dflBdcviMvLGgT3EaAbFJESor3AOfg5jRBxR0c
-----END RSA PRIVATE KEY-----


)EOF";
// Amazon Trust Services(ATS) 엔드포인트 CA 인증서 (서버인증 > "RSA 2048비트 키: Amazon Root CA 1" 다운로드)
const char ca_str[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
WlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";
